[theme]
primaryColor = "#0A1D3B"                # SGGH navy
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F4"
textColor = "#000000"
font = "sans serif"
[server]
port = 8000
enableCORS = false
headless = true
